<a href="https://colab.research.google.com/github/rockerritesh/Artifical-Neural-Network/blob/master/NPL_and_SENTIMENT_CLASSIFICATION_using_simple_NEURAL_NETWORK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

### ***Below  code is for Stemmer***

In [3]:

paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""
               

In [4]:
               
sentences = nltk.sent_tokenize(paragraph)
stemmer = PorterStemmer()


In [5]:
# Stemming
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i] = ' '.join(words)   

In [6]:
sentences

['I three vision india .',
 'In 3000 year histori , peopl world come invad us , captur land , conquer mind .',
 'from alexand onward , greek , turk , mogul , portugues , british , french , dutch , came loot us , took .',
 'yet done nation .',
 'We conquer anyon .',
 'We grab land , cultur , histori tri enforc way life .',
 'whi ?',
 'becaus respect freedom others.that first vision freedom .',
 'I believ india got first vision 1857 , start war independ .',
 'It freedom must protect nurtur build .',
 'If free , one respect us .',
 'My second vision india ’ develop .',
 'for fifti year develop nation .',
 'It time see develop nation .',
 'We among top 5 nation world term gdp .',
 'We 10 percent growth rate area .',
 'our poverti level fall .',
 'our achiev global recognis today .',
 'yet lack self-confid see develop nation , self-reli self-assur .',
 'isn ’ incorrect ?',
 'I third vision .',
 'india must stand world .',
 'becaus I believ unless india stand world , one respect us .',
 'onl

## ***Below code is for Lemmatizer***

In [7]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

In [8]:
sentences = nltk.sent_tokenize(paragraph)
lemmatizer = WordNetLemmatizer()

# Lemmatization
for i in range(len(sentences)):
    words = nltk.word_tokenize(sentences[i])
    words = [lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
    sentences[i] = ' '.join(words)      

In [9]:
sentences

['I three vision India .',
 'In 3000 year history , people world come invaded u , captured land , conquered mind .',
 'From Alexander onwards , Greeks , Turks , Moguls , Portuguese , British , French , Dutch , came looted u , took .',
 'Yet done nation .',
 'We conquered anyone .',
 'We grabbed land , culture , history tried enforce way life .',
 'Why ?',
 'Because respect freedom others.That first vision freedom .',
 'I believe India got first vision 1857 , started War Independence .',
 'It freedom must protect nurture build .',
 'If free , one respect u .',
 'My second vision India ’ development .',
 'For fifty year developing nation .',
 'It time see developed nation .',
 'We among top 5 nation world term GDP .',
 'We 10 percent growth rate area .',
 'Our poverty level falling .',
 'Our achievement globally recognised today .',
 'Yet lack self-confidence see developed nation , self-reliant self-assured .',
 'Isn ’ incorrect ?',
 'I third vision .',
 'India must stand world .',
 'Bec

Below code is for TFIDF

In [10]:
# Cleaning the texts
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [11]:

ps = PorterStemmer()
wordnet=WordNetLemmatizer()  #here i have used Lemmatizer
sentences = nltk.sent_tokenize(paragraph)
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [12]:
corpus

['three vision india',
 'year history people world come invaded u captured land conquered mind',
 'alexander onwards greek turk mogul portuguese british french dutch came looted u took',
 'yet done nation',
 'conquered anyone',
 'grabbed land culture history tried enforce way life',
 '',
 'respect freedom others first vision freedom',
 'believe india got first vision started war independence',
 'freedom must protect nurture build',
 'free one respect u',
 'second vision india development',
 'fifty year developing nation',
 'time see developed nation',
 'among top nation world term gdp',
 'percent growth rate area',
 'poverty level falling',
 'achievement globally recognised today',
 'yet lack self confidence see developed nation self reliant self assured',
 'incorrect',
 'third vision',
 'india must stand world',
 'believe unless india stand world one respect u',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand',
 'good fortune worked

In [48]:
# Creating the TF-IDF model
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
X = cv.fit_transform(corpus).toarray()

In [49]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.25883507, 0.30512561,
        0.        ],
       [0.        , 0.28867513, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [50]:
X.shape

(31, 114)

In [16]:
import numpy as np

In [93]:
p=np.random.rand(31,).reshape(31,1)

In [94]:
for i in range(30):
  if p[i]>0.5:
    p[i]=1
  else:
    p[i]=0

In [95]:
#float_array. astype(int)
u=p.astype(int)
u

array([[0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0]])

In [96]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
pca.fit(X)
x=pca.transform(X)

In [88]:
x

array([[ 0.58581936, -0.36031422],
       [-0.13347329,  0.01965025],
       [-0.10433007, -0.03603366],
       [-0.33741194,  0.02787448],
       [-0.13211641, -0.02922487],
       [-0.13122869, -0.12272707],
       [-0.05153062, -0.01331911],
       [ 0.27066536,  0.06214273],
       [ 0.44518269, -0.04732676],
       [ 0.03639224,  0.16009687],
       [ 0.10210849,  0.42433382],
       [ 0.50319981, -0.18284178],
       [-0.29723889,  0.02472199],
       [-0.38767314,  0.01437153],
       [-0.16714565,  0.20634504],
       [-0.10433007, -0.03603366],
       [-0.10433007, -0.03603366],
       [-0.10433007, -0.03603366],
       [-0.34330505, -0.00068824],
       [-0.10433007, -0.03603366],
       [ 0.32686374, -0.29982682],
       [ 0.36693175,  0.41616725],
       [ 0.40760873,  0.5623561 ],
       [-0.0060381 ,  0.21603946],
       [-0.05772311,  0.09527026],
       [-0.04652604,  0.11935713],
       [ 0.01842093, -0.49313434],
       [-0.11957409, -0.04573908],
       [-0.11957409,

In [97]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,u,test_size=0.1)

In [61]:
x_train.shape

(27, 2)

In [62]:
y_train.shape

(27, 1)

In [83]:
y_test[3]

array([1])

In [98]:
from sklearn.linear_model import LogisticRegression
reg= LogisticRegression()
reg.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [99]:
reg.predict(x_test)

array([0, 0, 0, 0])

In [100]:
y_test

array([[0],
       [1],
       [0],
       [0]])

In [ ]:
#From her we are going to start mini project of sentiment classification.

In [77]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, mean_squared_error, mean_absolute_error, r2_score

In [18]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization, Activation
from keras.optimizers import Adam
from keras.callbacks import EarlyStopping
from keras.utils.np_utils import to_categorical
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, KFold
import keras.backend as K
from keras.wrappers.scikit_learn import KerasClassifier

Using TensorFlow backend.


In [1]:
import pandas as pd
df=pd.read_csv('train.csv')
df

textID  ... sentiment
0      cb774db0d1  ...   neutral
1      549e992a42  ...  negative
2      088c60f138  ...  negative
3      9642c003ef  ...  negative
4      358bd9e861  ...  negative
...           ...  ...       ...
27476  4eac33d1c0  ...  negative
27477  4f4c4fc327  ...  negative
27478  f67aae2310  ...  positive
27479  ed167662a5  ...  positive
27480  6f7127d9d7  ...   neutral

[27481 rows x 4 columns]

In [2]:
def missing_value_of_data(data):
    total=data.isnull().sum().sort_values(ascending=False)
    percentage=round(total/data.shape[0]*100,2)
    return pd.concat([total,percentage],axis=1,keys=['Total','Percentage'])

In [3]:
f=missing_value_of_data(df)
f

Total  Percentage
selected_text      1         0.0
text               1         0.0
sentiment          0         0.0
textID             0         0.0

In [4]:
df=df.dropna()

In [5]:
x=df.iloc[:,2].values
x

array(['I`d have responded, if I were going', 'Sooo SAD', 'bullying me',
       ..., 'Yay good for both of you.', 'But it was worth it  ****.',
       'All this flirting going on - The ATG smiles. Yay.  ((hugs)'],
      dtype=object)

In [6]:
# Creating the TF-IDF model
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
X = cv.fit_transform(x).toarray()

In [7]:
#print(X)
X.shape

(27480, 17620)

In [8]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
Y=df.iloc[:,3]
Y

0         neutral
1        negative
2        negative
3        negative
4        negative
           ...   
27476    negative
27477    negative
27478    positive
27479    positive
27480     neutral
Name: sentiment, Length: 27480, dtype: object

In [10]:
cat=df['sentiment']
w=pd.get_dummies(cat)
w


negative  neutral  positive
0             0        1         0
1             1        0         0
2             1        0         0
3             1        0         0
4             1        0         0
...         ...      ...       ...
27476         1        0         0
27477         1        0         0
27478         0        0         1
27479         0        0         1
27480         0        1         0

[27480 rows x 3 columns]

In [11]:
t=w.iloc[:,[0,1,2]].values
t

array([[0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0]], dtype=uint8)

In [12]:
from sklearn.decomposition import PCA
pca=PCA(n_components=8)
pca.fit(X)
x=pca.transform(X)

In [33]:
np.array(x[1])

array([-0.02015769, -0.02006888, -0.02860277, -0.01587131,  0.57958544,
       -0.03712078, -0.05242988, -0.01738831])

In [15]:
t.shape

(27480, 3)

In [16]:
from numpy import asarray
from numpy import save
data=x
save('data.npy',data)

In [17]:
save('result.npy',t)

In [40]:
model = Sequential()
model.add(Dense(256, input_shape=(8,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile('adam', 'categorical_crossentropy', metrics=['accuracy'])

In [41]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_21 (Dense)             (None, 256)               2304      
_________________________________________________________________
dense_22 (Dense)             (None, 128)               32896     
_________________________________________________________________
dense_23 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_24 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_25 (Dense)             (None, 16)                528       
_________________________________________________________________
dense_26 (Dense)             (None, 8)                 136       
_________________________________________________________________
dense_27 (Dense)             (None, 3)                

In [42]:
history = model.fit(x, t, verbose=1, epochs=50)


Epoch 1/50
27480/27480 [==============================] - 2s 71us/step - loss: 0.8383 - accuracy: 0.6195
Epoch 2/50
27480/27480 [==============================] - 2s 62us/step - loss: 0.7803 - accuracy: 0.6493
Epoch 3/50
27480/27480 [==============================] - 2s 63us/step - loss: 0.7642 - accuracy: 0.6614
Epoch 4/50
27480/27480 [==============================] - 2s 60us/step - loss: 0.7527 - accuracy: 0.6650
Epoch 5/50
27480/27480 [==============================] - 2s 60us/step - loss: 0.7478 - accuracy: 0.6679
Epoch 6/50
27480/27480 [==============================] - 2s 62us/step - loss: 0.7404 - accuracy: 0.6747
Epoch 7/50
27480/27480 [==============================] - 2s 58us/step - loss: 0.7361 - accuracy: 0.6783
Epoch 8/50
27480/27480 [==============================] - 2s 61us/step - loss: 0.7335 - accuracy: 0.6780
Epoch 9/50
27480/27480 [==============================] - 2s 61us/step - loss: 0.7280 - accuracy: 0.6809
Epoch 10/50
27480/27480 [==============================

In [44]:
tf=pd.read_csv('test.csv')
missing=missing_value_of_data(df)
print(missing)
tf=tf.dropna()
tf

               Total  Percentage
sentiment          0         0.0
selected_text      0         0.0
text               0         0.0
textID             0         0.0


textID                                               text sentiment
0     f87dea47db  Last session of the day  http://twitpic.com/67ezh   neutral
1     96d74cb729   Shanghai is also really exciting (precisely -...  positive
2     eee518ae67  Recession hit Veronique Branquinho, she has to...  negative
3     01082688c6                                        happy bday!  positive
4     33987a8ee5             http://twitpic.com/4w75p - I like it!!  positive
...          ...                                                ...       ...
3529  e5f0e6ef4b  its at 3 am, im very tired but i can`t sleep  ...  negative
3530  416863ce47  All alone in this old house again.  Thanks for...  positive
3531  6332da480c   I know what you mean. My little dog is sinkin...  negative
3532  df1baec676  _sutra what is your next youtube video gonna b...  positive
3533  469e15c5a8   http://twitpic.com/4woj2 - omgssh  ang cute n...  positive

[3534 rows x 3 columns]

In [45]:
x_test=tf.iloc[:,1].values
x_test

array(['Last session of the day  http://twitpic.com/67ezh',
       ' Shanghai is also really exciting (precisely -- skyscrapers galore). Good tweeps in China:  (SH)  (BJ).',
       'Recession hit Veronique Branquinho, she has to quit her company, such a shame!',
       ...,
       ' I know what you mean. My little dog is sinking into depression... he wants to move someplace tropical',
       '_sutra what is your next youtube video gonna be about? I love your videos!',
       ' http://twitpic.com/4woj2 - omgssh  ang cute ng bby.!'],
      dtype=object)

In [46]:
# Creating the TF-IDF model
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
X_test = cv.fit_transform(x_test).toarray()
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [48]:
from sklearn.decomposition import PCA
pca=PCA(n_components=8)
pca.fit(X_test)
x_test=pca.transform(X_test)

In [50]:
x_test.shape

(3534, 8)

In [51]:
y_pred=model.predict(x_test)

In [55]:
np.argmax(y_pred[2])

0

In [85]:
Y_test=tf.iloc[:,2]
cate=tf['sentiment']
y_test=pd.get_dummies(cate)
y_test =y_test.values

In [90]:
print(np.argmax(y_pred[4]))
print(np.argmax(y_test[4]))

2
2


In [92]:
g=model.predict_classes(x_test)
g.shape

(3534,)

In [93]:
h=np.argmax(y_test,axis=1)
h.shape

(3534,)

In [94]:
confusion_matrix(g,h)

array([[137, 227, 119],
       [403, 431, 381],
       [461, 772, 603]])